name: HTML

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        java: [8.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          architecture: x64
      - run: npm ci
      - run: npm run build
      - run: npm run html
